name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-and-push:

    strategy:
      matrix:
        platforms: [linux/amd64, linux/arm64]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x

    - name: Get Git Version
      run: |
        dotnet tool install -g nbgv
        GITVERSION=$(nbgv get-version --format json | jq -r '.Cloud.BuildNumber')
        echo "GITVERSION=$GITVERSION" >> $GITHUB_ENV

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .devcontainer
        file: .devcontainer/Dockerfile
        platforms: ${{ matrix.platforms }}
        push: true
        tags: |
          ghcr.io/lachdawine/devcontainer-cpp:latest,
          ghcr.io/lachdawine/devcontainer-cpp:${{ env.GITVERSION }}
        labels: |
          org.opencontainers.image.title=devcontainer-cpp
          org.opencontainers.image.description="Development container for C++ projects with official LLVM-18, based on the official Visual Studio Code devcontainer image."
          org.opencontainers.image.licenses=MIT
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
