name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build on'
        required: true
        default: 'main'

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .devcontainer
        file: .devcontainer/Dockerfile
        platforms: ${{ matrix.platforms }}
        push: true
        tags: ghcr.io/lachdawine/devcontainer-cpp:latest
        outputs: type=image, name=lachdawine/devcontainer-cpp:latest,repository=ghcr.io/lachdawine/devcontainer-cpp,registry=ghcr.io,annotation-index.org.opencontainers.image.description=cpp devcontainer multi-arch
