name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build .devcontainer --file .devcontainer/Dockerfile --tag ghcr.io/lachdawine/devcontainer-cpp:latest
    - name: Push the Docker image
      run: docker push ghcr.io/lachdawine/devcontainer-cpp:latest
